[features]
seeds = false

[programs.localnet]
so_lution = "AhTPm4QecF67HhvFnYVJkM9jrgMwJcJNC3ULTHnaxdkX"
[programs.devnet]
so_lution = "AhTPm4QecF67HhvFnYVJkM9jrgMwJcJNC3ULTHnaxdkX"
[programs.mainnet]
so_lution = "AhTPm4QecF67HhvFnYVJkM9jrgMwJcJNC3ULTHnaxdkX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
reset = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/reset.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/so_lution.json app/src/idl/so_lution.json"
