[features]
seeds = false

[programs.localnet]
so_lution = "AQJ7RmbJtwGHru6aimiLriPZ4gTs7q5NnzeetyWgNfxo"
[programs.devnet]
so_lution = "AQJ7RmbJtwGHru6aimiLriPZ4gTs7q5NnzeetyWgNfxo"
[programs.mainnet]
so_lution = "AQJ7RmbJtwGHru6aimiLriPZ4gTs7q5NnzeetyWgNfxo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/so_lution.json app/src/idl/so_lution.json"
