version: 0.2

phases:
  install:
    commands:
      - npm i yarn@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo "Installing dependencies"
      - cd app && yarn
  build:
    commands:
      - echo "Building VueJS app"
      - cd app && yarn run build:devnet
  post_build:
    commands:
      - echo "Uploading to S3 bucket"
      - cd app && aws s3 sync ./dist $S3_BUCKET
